language: php

php:
    - 7.0
    - 7.1

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/30886f28c25b1e31088f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
