language: php

github_token: $GITHUB_TOKEN

services:
    - postgresql

matrix:
    include:
        - php: 7.1.3
          env: REDIS_HOST=127.0.0.1
        - php: 7.2
          env: REDIS_HOST=127.0.0.1
        - php: 7.3
          env: REDIS_HOST=127.0.0.1

services:
    - redis-server
    - postgresql

before_script:
    - travis_retry composer self-update
    - travis_retry composer config --global github-protocols https
    - travis_retry composer install --no-interaction --prefer-source
    - psql -c 'create database testing;' -U postgres
    - psql -c "CREATE USER homestead WITH PASSWORD 'secret';" -U postgres

after_success:
    - travis_retry php vendor/bin/php-coveralls -v

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/30886f28c25b1e31088f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
