language: php

github_token: $GITHUB_TOKEN

services:
  - postgresql
  - redis-server

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
  global:
  - REDIS_HOST=127.0.0.1

matrix:
  include:
    - php: 7.3
    - php: 7.4

before_script:
  - travis_retry composer self-update;
  - travis_retry composer config --global github-protocols https;
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then travis_retry composer config http-basic.nova.laravel.com $NOVA_USERNAME $NOVA_PASSWORD; fi'
  - travis_retry composer install --no-interaction --prefer-source;
  - if php -v | grep -q 'Xdebug'; then phpenv config-rm xdebug.ini; fi
  - pecl install pcov
  - psql -c "CREATE DATABASE testing;" -U postgres
  - psql -c "CREATE USER homestead WITH PASSWORD 'secret';" -U postgres

script:
  - mkdir -p build/logs
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml --exclude-group nova; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then php vendor/bin/phpunit -c phpunit.xml.dist  --coverage-clover build/logs/clover.xml; fi'

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/30886f28c25b1e31088f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
